// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaIgNLJ9V_AmX11vJb1l0nGophOZQdFu4',
    appId: '1:873312856759:web:479c278168b6b2c3d6bb32',
    messagingSenderId: '873312856759',
    projectId: 'fl-afc82',
    authDomain: 'fl-afc82.firebaseapp.com',
    storageBucket: 'fl-afc82.firebasestorage.app',
    measurementId: 'G-769KYF0D7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcCsVAxG2arh86W2jcSgz8NvM5bO1l4v8',
    appId: '1:873312856759:android:4c4193a602b319bbd6bb32',
    messagingSenderId: '873312856759',
    projectId: 'fl-afc82',
    storageBucket: 'fl-afc82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzrMCFrxJjfTPEPRT7c7aUaT3XXfpxMus',
    appId: '1:873312856759:ios:62b34dbb0643c051d6bb32',
    messagingSenderId: '873312856759',
    projectId: 'fl-afc82',
    storageBucket: 'fl-afc82.firebasestorage.app',
    iosBundleId: 'com.example.borderlessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzrMCFrxJjfTPEPRT7c7aUaT3XXfpxMus',
    appId: '1:873312856759:ios:62b34dbb0643c051d6bb32',
    messagingSenderId: '873312856759',
    projectId: 'fl-afc82',
    storageBucket: 'fl-afc82.firebasestorage.app',
    iosBundleId: 'com.example.borderlessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaIgNLJ9V_AmX11vJb1l0nGophOZQdFu4',
    appId: '1:873312856759:web:7888d7392fd4d222d6bb32',
    messagingSenderId: '873312856759',
    projectId: 'fl-afc82',
    authDomain: 'fl-afc82.firebaseapp.com',
    storageBucket: 'fl-afc82.firebasestorage.app',
    measurementId: 'G-RY2NW7K62J',
  );
}
